# Generated by Django 3.1.1 on 2021-02-10 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20210209_1357'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ['last_name', 'first_name'], 'permissions': (('can_modify_author_list', 'Add, Edit or Delete an Author'),)},
        ),
    ]
